#!/bin/bash

app_command='ukuu-gtk'

if [ `id -u` -eq 0 ]; then
	#user is admin
	${app_command}
else
	#user is not admin
	if command -v pkexec >/dev/null 2>&1; then
		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY ${app_command}
	elif command -v gksu >/dev/null 2>&1; then
		gksu ${app_command}
	elif command -v sudo >/dev/null 2>&1; then
		x-terminal-emulator -e "sudo ${app_command}"
	elif command -v su >/dev/null 2>&1; then
		x-terminal-emulator -e "su - -c '${app_command}'"
	else
		x-terminal-emulator -e "echo 'Command must be run as root user: ${app_command}'"
	fi
fi
